INSERT INTO ADDRESS (DESCRIPTION) VALUES ('1st street');
INSERT INTO ADDRESS (DESCRIPTION) VALUES ('2nd street');
INSERT INTO ADDRESS (DESCRIPTION) VALUES ('3rd street');

INSERT INTO LOCAL_SERVICE (DESCRIPTION) VALUES ('Post Office A');
INSERT INTO LOCAL_SERVICE (DESCRIPTION) VALUES ('Post Office B');
INSERT INTO LOCAL_SERVICE (DESCRIPTION) VALUES ('Post Office C');


INSERT INTO ORDER_TABLE (DESTINATION_ADDRESS_ID, SOURCE_ADDRESS_ID) VALUES (1, 3);
INSERT INTO ORDER_TABLE (DESTINATION_ADDRESS_ID, SOURCE_ADDRESS_ID) VALUES (2, 3);

--order 1
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-10-01 16:00:00.69'}, 'DEPARTED', 3,1,NULL,1);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-10-01 18:00:00.69'}, 'IN_TRANSIT', 3,2,1,1);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-10-02 18:00:00.69'}, 'IN_TRANSIT', 2,3,2,1);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-10-03 08:00:00.69'}, 'LAST_MILE', 2, NULL,3,1);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-10-03 16:00:00.69'}, 'ARRIVED', 1, NULL,NULL,1);

UPDATE ORDER_TABLE SET CURRENT_POSITION_ID=5 WHERE ID=1;


--order 2
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-09-01 16:00:00.69'}, 'DEPARTED', 3,1,NULL,2);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-09-01 18:00:00.69'}, 'IN_TRANSIT', 3,2,1,2);
INSERT INTO TRACKING (NOW, STATUS, ADDRESS_ID, DESTINATION_SERVICE_ID, SOURCE_SERVICE_ID, ORDER_ID)
VALUES({ts '2021-09-02 18:00:00.69'}, 'IN_TRANSIT', 2,3,2,2);

UPDATE ORDER_TABLE SET CURRENT_POSITION_ID=8 WHERE ID=2;
